FROM alpine
WORKDIR /root/task
#Install git
RUN apt-get update \
    && apt-get install -y git

RUN git clone https://github.com/AbdelrahmanElmasry/EncryptionTask.git

RUN apk add openjdk8
ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk
ENV PATH $PATH:$JAVA_HOME/bin

WORKDIR /root/task/EncryptionTask/encryptionApp/src

RUN javac App.java

ENTRYPOINT java App